---
- name: Playbook for Kafka Node
  hosts: kafkaredis1
  vars:    
    
    upass: somestrangething647jf
  gather_facts: no
  any_errors_fatal: false
  become: yes
  tasks:
    - name: delete the user kafka
      shell: userdel -rf kafka

    - name: Create user kafka
      user:
        name: kafka
        password: "{{ upass | password_hash('sha512') }}"
        groups:
          - sudo
        state: present

    - name: Install open JDK
      apt: name=openjdk-8-jdk state=present
      tags: java

    - name: create kafka direcory
      file: path={{kafka_dir}} state=directory owner=kafka

    - name: Download and unarchive kafka binary
      unarchive:
        extra_opts: ['--strip=1']
        src: https://www.apache.org/dist/kafka/{{kafka_version}}/kafka_{{scala_version}}-{{kafka_version}}.tgz
        dest: '{{kafka_dir}}'
        remote_src: yes

    - name: update the server property files
      lineinfile:
        path: '{{kafka_dir}}/config/server.properties'
        line: delete.topic.enable = true

    - name: Get External IP 
      shell: ifconfig eth0 | grep  -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"  | head -n1 > /root/externalip.txt
      
    - name: Get all internal IPs
      command: cat /root/externalip.txt
      register: externalip
      changed_when: false


    - name: Create kafka service
      template: src=kafka.service dest=/etc/systemd/system/kafka.service

    - name: Create zookeeper service
      template: src=zookeeper.service dest=/etc/systemd/system/zookeeper.service

    - name: add the server IP
      lineinfile:
        path: /home/kafka/kafka/config/server.properties
        line: advertised.listeners=PLAINTEXT://{{externalip.stdout}}:9092
        insertafter: '#advertised.listeners=PLAINTEXT'

    - name: Remove the zoookeper line
      lineinfile:
        path: /home/kafka/kafka/config/server.properties
        state: absent
        regexp: 'zookeeper.connect=localhost:2181'

    - name: add zookeper IP
      lineinfile:
        path: /home/kafka/kafka/config/server.properties
        line: zookeeper.connect={{externalip.stdout}}:2181
        insertafter: '# root directory for all kafka znodes.'

    - name: Make sure a service is running
      systemd:
        state: started
        name: kafka
        daemon_reload: yes

    - name: Check for proper install
      shell: journalctl -u kafka
      register: kafkastatus
      changed_when: false

    - debug: msg="{{kafkastatus.stdout}}"


      
