---
- name: Playbook for Kafka Node
  hosts: kafkaredis1
  vars:    
    kafka_version: 2.2.0
    scala_version: 2.12
    kafka_dir: /home/kafka/kafka
    upass: somestrangething647jf
  gather_facts: no
  any_errors_fatal: false
  become: yes
  tasks:
    - name: Create user kafka
      user:
        name: kafka
        password: "{{ upass | password_hash('sha512') }}"
        groups:
          - sudo
        state: present

    - name: Install open JDK
      apt: name=openjdk-8-jdk state=present
      tags: java

    - name: create kafka direcory
      file: path={{kafka_dir}} state=directory owner=kafka

    - name: Download and unarchive kafka binary
      unarchive:
        extra_opts: ['--strip=1']
        src: https://www.apache.org/dist/kafka/{{kafka_version}}/kafka_{{scala_version}}-{{kafka_version}}.tgz
        dest: '{{kafka_dir}}'
        remote_src: yes

    - name: update the server property files
      lineinfile:
        path: '{{kafka_dir}}/config/server.properties'
        line: delete.topic.enable = true


    - name: Create kafka service
      template: src=kafka.service dest=/etc/systemd/system/kafka.service

    - name: Create zookeeper service
      template: src=zookeeper.service dest=/etc/systemd/system/zookeeper.service

    - name: Make sure a service is running
      systemd:
        state: started
        name: kafka
        daemon_reload: yes

    - name: Check for proper install
      shell: journalctl -u kafka
      register: kafkastatus
      changed_when: false

    - debug: msg="{{kafkastatus.stdout}}"


      
